version: '3'

services:
  postgresql:
    container_name: clientexp-db
    image: postgres:12.2-alpine
    env_file:
      - clientexp.env
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
